name: Deploy Staging Docker

on:
  push:
    branches:
    - ci

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: SHA Short
        id: sha
        run: echo "SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.export
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-example:${{ steps.sha.outputs.SHA_SHORT }}
      
      - name: Deploy to VPS [export]
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/${{ github.sha }}"
          chmod 600 "$HOME/.ssh/${{ github.sha }}"
          
          ssh -t -i $HOME/.ssh/${{ github.sha }} -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/nextjs-example:${{ steps.sha.outputs.SHA_SHORT }}"
          docker pull $IMAGE_NAME
          docker stop nextjs-example
          docker rm nextjs-example
          docker run -d --name nextjs-example -p 3000:80 $IMAGE_NAME
          EOF

      - name: Notify
        run: |
          curl -XPOST -H 'Content-type: application/json' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          --data '{
            "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
            "parse_mode": "MarkdownV2",
            "text": "
            ðŸš€ *Deployed*
  
            Workflow: ${{ github.workflow }}
  
            ðŸ‘‰ Actions: [Here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
  
            Repository: [Here](https://github.com/${{ github.repository }})
  
            ðŸ“„ See changes: [Here](https://github.com/${{ github.repository }}/commit/${{github.sha}})
            "
          }'